kind: pipeline
name: docker

trigger:
  branch:
    - release-v1.28

workspace:
  path: /go/src/k8s.io/kubernetes

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY
    depends_on:
      - s3-cache

  - name: golang-kube-apiserver
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/golang:1.22
    environment:
      KUBE_GIT_VERSION: v1.28.13-beagle
      KUBE_BUILD_PLATFORMS: linux/amd64 linux/arm64
      KUBE_GIT_TREE_STATE: archive
    commands:
      # - git apply .beagle/v1.26-mips64le.patch
      - make kube-apiserver
    depends_on:
      - fetch

  - name: golang-kube-controller-manager
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/golang:1.22
    environment:
      KUBE_GIT_VERSION: v1.28.13-beagle
      KUBE_BUILD_PLATFORMS: linux/amd64 linux/arm64
      KUBE_GIT_TREE_STATE: archive
    commands:
      - make kube-controller-manager
    depends_on:
      - golang-kube-apiserver

  - name: golang-kube-scheduler
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/golang:1.22
    environment:
      KUBE_GIT_VERSION: v1.28.13-beagle
      KUBE_BUILD_PLATFORMS: linux/amd64 linux/arm64
      KUBE_GIT_TREE_STATE: archive
    commands:
      - make kube-scheduler
    depends_on:
      - golang-kube-controller-manager

  - name: golang-kubelet
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/golang:1.22
    environment:
      KUBE_GIT_VERSION: v1.28.13-beagle
      KUBE_BUILD_PLATFORMS: linux/amd64 linux/arm64
      KUBE_GIT_TREE_STATE: archive
      KUBE_STATIC_OVERRIDES: cmd/kubelet
    commands:
      - make kubelet
    depends_on:
      - golang-kube-scheduler

  - name: golang-kube-proxy
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/golang:1.22
    environment:
      KUBE_GIT_VERSION: v1.28.13-beagle
      KUBE_BUILD_PLATFORMS: linux/amd64 linux/arm64
      KUBE_GIT_TREE_STATE: archive
    commands:
      - make kube-proxy
    depends_on:
      - golang-kubelet

  - name: golang-kubectl
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/golang:1.22
    environment:
      KUBE_GIT_VERSION: v1.28.13-beagle
      KUBE_BUILD_PLATFORMS: linux/amd64 linux/arm64
      KUBE_GIT_TREE_STATE: archive
    commands:
      - make kubectl
    depends_on:
      - golang-kube-proxy

  - name: docker-kube-apiserver-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-base:v1.3.0-amd64
      dockerfile: .beagle/kube-apiserver.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-apiserver
      version: "v1.28.13-beagle"
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-apiserver

  - name: docker-kube-apiserver-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-base:v1.3.0-arm64
      dockerfile: .beagle/kube-apiserver.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-apiserver
      version: "v1.28.13-beagle"
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-apiserver

  - name: docker-kube-apiserver-arch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-apiserver:v1.28.13-beagle-ARCH
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-apiserver:v1.28.13-beagle
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-kube-apiserver-amd64
      - docker-kube-apiserver-arm64

  - name: docker-kube-controller-manager-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-base:v1.3.0-amd64
      dockerfile: .beagle/kube-controller-manager.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-controller-manager
      version: "v1.28.13-beagle"
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-controller-manager

  - name: docker-kube-controller-manager-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-base:v1.3.0-arm64
      dockerfile: .beagle/kube-controller-manager.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-controller-manager
      version: "v1.28.13-beagle"
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-controller-manager

  - name: docker-kube-controller-manager-arch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-controller-manager:v1.28.13-beagle-ARCH
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-controller-manager:v1.28.13-beagle
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-kube-controller-manager-amd64
      - docker-kube-controller-manager-arm64

  - name: docker-kube-scheduler-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-base:v1.3.0-amd64
      dockerfile: .beagle/kube-scheduler.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-scheduler
      version: "v1.28.13-beagle"
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-scheduler

  - name: docker-kube-scheduler-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-base:v1.3.0-arm64
      dockerfile: .beagle/kube-scheduler.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-scheduler
      version: "v1.28.13-beagle"
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-scheduler

  - name: docker-kube-scheduler-arch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-scheduler:v1.28.13-beagle-ARCH
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-scheduler:v1.28.13-beagle
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-kube-scheduler-amd64
      - docker-kube-scheduler-arm64

  - name: docker-kubelet-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      dockerfile: .beagle/kubelet.dockerfile
      cwd: _output/local/bin
      repo: wod/kubelet
      version: "v1.28.13-beagle"
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kubelet

  - name: docker-kubelet-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      dockerfile: .beagle/kubelet.dockerfile
      cwd: _output/local/bin
      repo: wod/kubelet
      version: "v1.28.13-beagle"
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kubelet

  - name: docker-kubelet-arch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry-vpc.cn-qingdao.aliyuncs.com/wod/kubelet:v1.28.13-beagle-ARCH
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/kubelet:v1.28.13-beagle
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-kubelet-amd64
      - docker-kubelet-arm64

  - name: docker-kube-proxy-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-iptables:v1.4.0-amd64
      dockerfile: .beagle/kube-proxy.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-proxy
      version: "v1.28.13-beagle"
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-proxy

  - name: docker-kube-proxy-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/debian-iptables:v1.4.0-arm64
      dockerfile: .beagle/kube-proxy.dockerfile
      cwd: _output/local/bin
      repo: wod/kube-proxy
      version: "v1.28.13-beagle"
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kube-proxy

  - name: docker-kube-proxy-arch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-proxy:v1.28.13-beagle-ARCH
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/kube-proxy:v1.28.13-beagle
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-kube-proxy-amd64
      - docker-kube-proxy-arm64

  - name: docker-kubectl-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      dockerfile: .beagle/kubectl.dockerfile
      cwd: _output/local/bin
      repo: wod/kubectl
      version: "v1.28.13-beagle"
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kubectl

  - name: docker-kubectl-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      dockerfile: .beagle/kubectl.dockerfile
      cwd: _output/local/bin
      repo: wod/kubectl
      version: "v1.28.13-beagle"
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang-kubectl

  - name: docker-kubectl-arch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry-vpc.cn-qingdao.aliyuncs.com/wod/kubectl:v1.28.13-beagle-ARCH
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/kubectl:v1.28.13-beagle
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-kubectl-amd64
      - docker-kubectl-arm64

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
